#!/data/data/com.termux/files/usr/bin/bash

if [ "${UID}" != "0" ]; then
    # sshd
    tsu -a -e -c "${0}"
    exit 0
fi

# we are supposed to be root here
# and are able to call iptables
if ! /system/bin/iptables -L PREROUTING -t nat -n | grep -q 8022; then
  echo "setting up redirect form port 22 to 8022"
  /system/bin/iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 8022
fi
